# Generated by Django 5.0.1 on 2025-02-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_user_alter_recipe_user_alter_savedrecipe_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
